apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sd.fullname" . }}
  labels:
    {{- include "sd.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sd.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ["tail", "-f", "/etc/hosts"]
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.persistence.hostPaths }}
            - mountPath: {{ .mountPath }}
              name: {{ .name | camelcase | lower }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- range .Values.persistence.pvcs }}
            - mountPath: {{ .mountPath }}
              name: {{ .name | camelcase | lower }}-{{ .subPath | replace "/" "-" }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
            {{- if .Values.persistence.sharedPvc.sharedExistingClaim }}
            {{- range .Values.persistence.sharedPvc.subPaths }}
            - mountPath: "{{ $.Values.persistence.sharedPvc.mountPathBase }}/{{ . }}"
              name: shared-data
              {{- if . }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
            {{- end }}
            - mountPath: {{ .Values.persistence.sharedPvc.mountPathBase }}/output
              name: output
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- range .Values.persistence.hostPaths }}
        - name: {{ .name | camelcase | lower }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
      {{- end }}
      {{- range .Values.persistence.pvcs }}
        - name: {{ .name | camelcase | lower }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
      {{- end }}
      {{- if .Values.persistence.sharedPvc.sharedExistingClaim }}
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.sharedPvc.sharedExistingClaim }}
      {{- end }}
        - name: output
          emptyDir:
            medium: Memory
