{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sd.serviceAccountName" . }}
  labels:
    {{- include "sd.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sd
  namespace: sd
subjects:
- kind: ServiceAccount
  name: sd
  namespace: sd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  # Lock clusterrole down to sd namespace
  # namespace: sd
  apiGroup: rbac.authorization.k8s.io
