apiVersion: v1
kind: Service
metadata:
  name: {{ include "sd.fullname" . }}
  labels:
    {{- include "sd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.port }}
      port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sd.selectorLabels" . | nindent 4 }}
